config/routes.rb
Foxhall::Application.routes.draw do
  resources :messages

  resources :features

  resources :feature_types

  resources :homes

  resources :collections

  resources :communities

  root to: 'pages#home'
end

app/controllers/feature_types_controller.rb
class FeatureTypesController < ApplicationController
  before_action :set_feature_type, only: [:show, :edit, :update, :destroy]

  # GET /feature_types
  # GET /feature_types.json
  def index
    @feature_types = FeatureType.all
  end

  # GET /feature_types/1
  # GET /feature_types/1.json
  def show
  end

  # GET /feature_types/new
  def new
    @feature_type = FeatureType.new
  end

  # GET /feature_types/1/edit
  def edit
  end

  # POST /feature_types
  # POST /feature_types.json
  def create
    @feature_type = FeatureType.new(feature_type_params)

    respond_to do |format|
      if @feature_type.save
        format.html { redirect_to @feature_type, notice: 'Feature type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @feature_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @feature_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feature_types/1
  # PATCH/PUT /feature_types/1.json
  def update
    respond_to do |format|
      if @feature_type.update(feature_type_params)
        format.html { redirect_to @feature_type, notice: 'Feature type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @feature_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feature_types/1
  # DELETE /feature_types/1.json
  def destroy
    @feature_type.destroy
    respond_to do |format|
      format.html { redirect_to feature_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feature_type
      @feature_type = FeatureType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feature_type_params
      params.require(:feature_type).permit(:name)
    end
end

app/views/feature_types/_form.html.erb
<%= form_for(@feature_type) do |f| %>
  <% if @feature_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feature_type.errors.count, "error") %> prohibited this feature_type from being saved:</h2>

      <ul>
      <% @feature_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feature_types/edit.html.erb
<h1>Editing feature_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @feature_type %> |
<%= link_to 'Back', feature_types_path %>

app/views/feature_types/index.html.erb
<h1>Listing feature_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @feature_types.each do |feature_type| %>
      <tr>
        <td><%= feature_type.name %></td>
        <td><%= link_to 'Show', feature_type %></td>
        <td><%= link_to 'Edit', edit_feature_type_path(feature_type) %></td>
        <td><%= link_to 'Destroy', feature_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feature type', new_feature_type_path %>

app/views/feature_types/new.html.erb
<h1>New feature_type</h1>

<%= render 'form' %>

<%= link_to 'Back', feature_types_path %>

app/views/feature_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @feature_type.name %>
</p>

<%= link_to 'Edit', edit_feature_type_path(@feature_type) %> |
<%= link_to 'Back', feature_types_path %>