config/routes.rb
Foxhall::Application.routes.draw do
  resources :messages

  resources :features

  resources :feature_types

  resources :homes

  resources :collections

  resources :communities

  root to: 'pages#home'
end

app/models/community.rb
class Community < ActiveRecord::Base
  has_one :address, as: :addressable, :dependent => :destroy

  validates :name, uniqueness: true, presence: true

  accepts_nested_attributes_for :address
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: [:show, :edit, :update, :destroy]

  # GET /communities
  # GET /communities.json
  def index
    @communities = Community.all
  end

  # GET /communities/1
  # GET /communities/1.json
  def show
  end

  # GET /communities/new
  def new
    @community = Community.new
    @community.address ||= Address.new
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities
  # POST /communities.json
  def create
    @community = Community.new(community_params)
    @community.address ||= Address.new(address_params)

    respond_to do |format|
      if @community.save
        format.html { redirect_to @community, notice: 'Community was successfully created.' }
        format.json { render action: 'show', status: :created, location: @community }
      else
        format.html { render action: 'new' }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1
  # PATCH/PUT /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to @community, notice: 'Community was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1
  # DELETE /communities/1.json
  def destroy
    @community.destroy
    respond_to do |format|
      format.html { redirect_to communities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_params
      params.require(:community).permit(:name, :description)
    end
    def address_params
      params.require(:address).permit(:line_1, :line_2, :city, :state, :zipcode)
    end
end

app/views/communities/_form.html.erb
<%= form_for(@community) do |f| %>
  <% if @community.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@community.errors.count, "error") %> prohibited this community from being saved:</h2>

      <ul>
      <% @community.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <%= fields_for @community.address do |address_fields| %>
    <div class="field">
      <%= address_fields.label :line_1 %><br>
      <%= address_fields.text_field :line_1 %>
    </div>
    <div class="field">
      <%= address_fields.label :line_2 %><br>
      <%= address_fields.text_field :line_2 %>
    </div>
    <div class="field">
      <%= address_fields.label :city %><br>
      <%= address_fields.text_field :city %>
    </div>
    <div class="field">
      <%= address_fields.label :state %><br>
      <%= address_fields.select :state, Address::States %>
    </div>
    <div class="field">
      <%= address_fields.label :zipcode %><br>
      <%= address_fields.text_field :zipcode %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/communities/edit.html.erb
<h1>Editing community</h1>

<%= render 'form' %>

<%= link_to 'Show', @community %> |
<%= link_to 'Back', communities_path %>

app/views/communities/index.html.erb
<h1>Listing communities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Address Line 1</th>
      <th>Address Line 2</th>
      <th>Address City</th>
      <th>Address State</th>
      <th>Address Zipcode</th>
    </tr>
  </thead>

  <tbody>
    <% @communities.each do |community| %>
      <tr>
        <td><%= community.name %></td>
        <td><%= community.description %></td>
        <td><%= community.address.line_1 %></td>
        <td><%= community.address.line_2 %></td>
        <td><%= community.address.city %></td>
        <td><%= community.address.state %></td>
        <td><%= community.address.zipcode %></td>
        <td><%= link_to 'Show', community %></td>
        <td><%= link_to 'Edit', edit_community_path(community) %></td>
        <td><%= link_to 'Destroy', community, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Community', new_community_path %>

app/views/communities/new.html.erb
<h1>New community</h1>

<%= render 'form' %>

<%= link_to 'Back', communities_path %>

app/views/communities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @community.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @community.description %>
</p>

<%= link_to 'Edit', edit_community_path(@community) %> |
<%= link_to 'Back', communities_path %>